/* PRIMEIRA FORMA NORMAL */ 

/* 
1- TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA

[AMARELO, AZUL, LARANJA, VERDE] --> CORES

[KA, FIESTA, UNO, CIVIC] --> CARROS 

2- TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA.
QUANDO O CAMPO FOR DIVISÍVEL 

3- TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO O REGISTRO COMO 
SENDO UNICO.
ISSO É O QUE CHAMAMOS DE CHAVE PRIMARIA OU PRIMARY KEY. 

NATURAL - PERTENCE AO REGISTRO
ARTIFICAL - CRIAMOS A CHAVE EX ID. 1, 2, 3, 4


*/

CREATE DATABASE COMERCIO;

USE COMERCIO; 
--Se é obrigatorio colocar not null
--NÃO PODE SE REPETIR, MAS NÃO É OBRIGATÓRIO

DROP TABLE CLIENTE; -- PARA APAGAR AS TABELAS


CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL, 
	SEXO ENUM('M', 'F') NOT NULL, 
	EMAIL VARCHAR(50) UNIQUE,	
	CPF VARCHAR(15) UNIQUE

);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL, 
	BAIRRO VARCHAR(30) NOT NULL, 
	CIDADE VARCHAR(30) NOT NULL, 
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE, 
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)

);


/* ENDERECO - obrigatorio
	CADASTRO DE SOMENTE UM
	
	TELEFONE - NAO obrigatorio
	CADASTRO DE MAIS DE UM (OPCIONAL)

*/

/*
	CHAVE ESTRANGEIRA É A CHAVE PRIMÁRIA DE UMA TABELA QUE
	ATÉ A OUTRA TABELA PARA FAZER REFERENCIA ENTRE
	REGISTROS


*/

/* EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTOS 1 X N A CHAVE ESTRANGEIRA FICARA SEMPRE NA CARDINALIDADE N */
