/*DELETE*/ 

INSERT INTO CLIENTE VALUES(NULL, 'XXXX', 'M', NULL, 'XXXXX');

DELETE FROM CLIENTE WHERE IDCLIENTE = 16; 


/* DDL - DATA DEFINITION LANGUAGE

*/

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(30) NOT NULL, 
	PRECO INT, 
	FRETE FLOAT(10, 2) NOT NULL

);