INSERT INTO CLIENTE VALUES(NULL, 'JOAO', 'M', 'joao@ig.com', '74565652344');
INSERT INTO CLIENTE VALUES(NULL,'FLAVIO','M','FLAVIO@IG.COM','4657765');
INSERT INTO CLIENTE VALUES(NULL,'ANDRE','M','ANDRE@GLOBO.COM','7687567');
INSERT INTO CLIENTE VALUES(NULL,'GIOVANA','F',NULL,'0876655');
INSERT INTO CLIENTE VALUES(NULL,'KARLA','M','KARLA@GMAIL.COM','545676778');
INSERT INTO CLIENTE VALUES(NULL,'DANIELE','M','DANIELE@GMAIL.COM','43536789');
INSERT INTO CLIENTE VALUES(NULL,'LORENA','M',NULL,'774557887');
INSERT INTO CLIENTE VALUES(NULL,'EDUARDO','M',NULL,'54376457');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','F','ANTONIO@IG.COM','12436767');
INSERT INTO CLIENTE VALUES(NULL,'ANTONIO','M','ANTONIO@UOL.COM','3423565');
INSERT INTO CLIENTE VALUES(NULL,'ELAINE','M','ELAINE@GLOBO.COM','32567763');
INSERT INTO CLIENTE VALUES(NULL,'CARMEM','M','CARMEM@IG.COM','787832213');
INSERT INTO CLIENTE VALUES(NULL,'ADRIANA','F','ADRIANA@GMAIL.COM','88556942');
INSERT INTO CLIENTE VALUES(NULL,'JOICE','F','JOICE@GMAIL.COM','55412256');

+-----------+---------+------+-------------------+-------------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF         |
+-----------+---------+------+-------------------+-------------+
|         1 | JOAO    | M    | joao@ig.com       | 74565652344 |
|         2 | FLAVIO  | M    | FLAVIO@IG.COM     | 4657765     |
|         3 | ANDRE   | M    | ANDRE@GLOBO.COM   | 7687567     |
|         4 | GIOVANA | F    | NULL              | 0876655     |
|         5 | KARLA   | M    | KARLA@GMAIL.COM   | 545676778   |
|         6 | DANIELE | M    | DANIELE@GMAIL.COM | 43536789    |
|         7 | LORENA  | M    | NULL              | 774557887   |
|         8 | EDUARDO | M    | NULL              | 54376457    |
|         9 | ANTONIO | F    | ANTONIO@IG.COM    | 12436767    |
|        10 | ANTONIO | M    | ANTONIO@UOL.COM   | 3423565     |
|        11 | ELAINE  | M    | ELAINE@GLOBO.COM  | 32567763    |
|        12 | CARMEM  | M    | CARMEM@IG.COM     | 787832213   |
|        13 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942    |
|        14 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256    |
+-----------+---------+------+-------------------+-------------+


DESC ENDERECO; 

INSERT INTO ENDERECO VALUES(NULL,'RUA ANTONIO SA', 'CENTRO', 'BELO HORIZONTE', 'MG', 4);
INSERT INTO ENDERECO VALUES(NULL,'RUA GUEDES','CASCADURA','B. HORIZONTE','MG',9);
INSERT INTO ENDERECO VALUES(NULL,'RUA MAIA LACERDA','ESTACIO','RIO DE JANEIRO','RJ',10);
INSERT INTO ENDERECO VALUES(NULL,'RUA VISCONDESSA','CENTRO','RIO DE JANEIRO','RJ',11);
INSERT INTO ENDERECO VALUES(NULL,'RUA NELSON MANDELA','COPACABANA','RIO DE JANEIRO','RJ',12);
INSERT INTO ENDERECO VALUES(NULL,'RUA ARAUJO LIMA','CENTRO','VITORIA','ES',13);
INSERT INTO ENDERECO VALUES(NULL,'RUA CASTRO ALVES','LEBLON','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES(NULL,'AV CAPITAO ANTUNES','CENTRO','CURITIBA','PR',2);
INSERT INTO ENDERECO VALUES(NULL,'AV CARLOS BARROSO','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES(NULL,'ALAMEDA SAMPAIO','BOM RETIRO','CURITIBA','PR',5);
INSERT INTO ENDERECO VALUES(NULL,'RUA DA LAPA','LAPA','SAO PAULO','SP',6);
INSERT INTO ENDERECO VALUES(NULL,'RUA GERONIMO','CENTRO','RIO DE JANEIRO','RJ',7);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',8);
INSERT INTO ENDERECO VALUES(NULL,'RUA GOMES FREIRE','CENTRO','RIO DE JANEIRO','RJ',14);

SELECT * FROM ENDERECO; 


DESC TELEFONE; 

INSERT INTO TELEFONE VALUES(NULL, 'CEL', '34546342', 5);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99656675',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','33567765',11);
INSERT INTO TELEFONE VALUES(NULL,'CEL','88668786',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','55689654',2);
INSERT INTO TELEFONE VALUES(NULL,'COM','88687979',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','88965676',4);
INSERT INTO TELEFONE VALUES(NULL,'CEL','89966809',7);
INSERT INTO TELEFONE VALUES(NULL,'COM','88679978',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99655768',8);
INSERT INTO TELEFONE VALUES(NULL,'RES','89955665',9);
INSERT INTO TELEFONE VALUES(NULL,'RES','77455786',10);
INSERT INTO TELEFONE VALUES(NULL,'RES','89766554',10);
INSERT INTO TELEFONE VALUES(NULL,'RES','77755785',11);
INSERT INTO TELEFONE VALUES(NULL,'COM','44522578',11);
