/* INSERT */ 

INSERT INTO CLIENTE VALUES(NULL, 'PAULA', 'M', NULL, '984535232');
INSERT INTO ENDERECO VALUES(NULL, 'RUA JOAQUIM SILVA', 'ALVORADA', 'NITEROI', 'RJ', 7);

/*FILTROS*/
SELECT * FROM CLIENTE 
WHERE SEXO = 'M';

/*UPDATE*/

SELECT * FROM CLIENTE 
WHERE IDCLIENTE = 15;

UPDATE CLIENTE 
SET SEXO = 'F'
WHERE IDCLIENTE = 15; 
