* UPDATE, INSERT E DELETE - DML */

INSERT INTO V_RELATORIO VALUES(
'ANDREIA', 'F', 'ADREIA@UOL.COM.BR', 'CEL', '87654383', 'CENTRO', 'VITORIA', 'ES'
);

ERROR 1394 (HY000): Can not insert into join view 'comercio.v_relatorio' without fields list


SELECT * FROM V_RELATORIO
WHERE SEXO = 'F'; 


/* ORDER BY*/

CREATE TABLE ALUNOS(
	NUMERO INT, 
	NOME VARCHAR(30)

);


INSERT INTO ALUNOS VALUES(1, 'JOAO');
INSERT INTO ALUNOS VALUES(1, 'MARIA');
INSERT INTO ALUNOS VALUES(2, 'ZOE');
INSERT INTO ALUNOS VALUES(2, 'ANDRE');
INSERT INTO ALUNOS VALUES(3, 'CLARA');
INSERT INTO ALUNOS VALUES(1, 'CLARA');
INSERT INTO ALUNOS VALUES(4, 'MAFRA');
INSERT INTO ALUNOS VALUES(5, 'JANAINA');
INSERT INTO ALUNOS VALUES(1, 'JANAINA');
INSERT INTO ALUNOS VALUES(3, 'MARCELO');
INSERT INTO ALUNOS VALUES(4, 'GIOVANI');
INSERT INTO ALUNOS VALUES(5, 'ANTONIO');
INSERT INTO ALUNOS VALUES(6, 'ANA');
INSERT INTO ALUNOS VALUES(6, 'VIVIANE');

/*NOME DA COLUNA*/ 
SELECT * FROM ALUNOS 
ORDER BY NUMERO;

/* INDICE DA COLUNA*/
SELECT * FROM ALUNOS 
ORDER BY 1;

SELECT * FROM ALUNOS 
ORDER BY 2;


/* ORDENANDO POR MAIS DE UMA COLUNA*/

SELECT * FROM ALUNOS 
ORDER BY NUMERO, NOME;

SELECT * FROM ALUNOS
ORDER BY 1, 2;

/* MESCLANDO ORDER BY COM PROJECAO*/

SELECT NOME FROM ALUNOS
ORDER BY 1, 2; 

SELECT NOME FROM ALUNOS 
ORDER BY NUMERO, NOME;


/* ORDER BY DESC / ASC */

SELECT * FROM ALUNOS 
ORDER BY 1, 2;

SELECT * FROM ALUNOS 
ORDER BY 1 ASC;

SELECT * FROM ALUNOS 
ORDER BY 1 DESC;

SELECT * FROM ALUNOS 
ORDER BY 1, 2 DESC;

SELECT * FROM ALUNOS 
ORDER BY 1 DESC, 2 DESC;


/* ORDENANDO COM JOINS */
 
SELECT C.NOME,
C.SEXO, 
C.EMAIL, 
T.TIPO, 
T.NUMERO, 
E.BAIRRO, 
E.CIDADE, 
E.ESTADO
FROM CLIENTE C 
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
ORDER BY 1;

SHOW TABLES; 

SELECT * FROM V_RELATORIO
ORDER BY 1; 


/*mudar o delimitador*/

DELIMITER 


/* STORED PROCEDURES (PROCEDIMENTOS ARMAZENADOS)*/

SELECT 'MAFRA';

DELIMITER $


CREATE PROCEDURE NOME()
BEGIN

	QUALQUER PROGRAMACAO;


END
$

CREATE PROCEDURE NOME_EMPRESA()
BEGIN

	SELECT 'UNIVERSIDADE DOS DADOS' AS EMPRESA;

END
$



CALL NOME_EMPRESA()$


DELIMITER ;

CALL NOME_EMPRESA();

/* PROCEDURES COM PARAMETROS*/

SELECT 10 + 10 AS CONTA; 

/*APAGAR PROCEDURE*/

DROP PROCEDURE CONTA; 


CREATE PROCEDURE CONTA(NUMERO1 INT, NUMERO2 INT)
BEGIN

	SELECT NUMERO1 + NUMERO2 AS CONTA;

END
$

CALL CONTA(100, 50)$
