/*PROCEDURES*/

CREATE DATABASE PROJETO2;

USE PROJETO2;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL, 
	HORAS INT(3) NOT NULL, 
	VALOR FLOAT(10,2) NOT NULL
);


INSERT INTO CURSOS VALUES(NULL, 'JAVA', 30, 500.00);
INSERT INTO CURSOS VALUES(NULL, 'FUNDAMENTOS DE BANCO DE DADOS', 40, 700.00);

DELIMITER #


CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30),
						   P_HORAS INT(3),
						   P_PRECO FLOAT(10,2))
BEGIN
	INSERT INTO CURSOS VALUES(NULL,P_NOME,P_HORAS,P_PRECO);
END
#

DELIMITER ;

CALL CAD_CURSO('BI SQL SERVER', 35, 3000.00);
CALL CAD_CURSO('POWER BI', 20, 1000.00);
CALL CAD_CURSO('TABLEAU', 30, 1200.00);

/* CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS*/

DELIMITER #

CREATE PROCEDURE CONSULTA()
BEGIN
	SELECT * FROM CURSOS;

END
#


UPDATE CURSOS
SET NOME = 'BI SQL SERVER'
WHERE IDCURSO = 3; 

UPDATE CURSOS
SET NOME = 'POWER BI'
WHERE IDCURSO = 4; 

UPDATE CURSOS
SET NOME = 'TABLEAU'
WHERE IDCURSO = 5;


/*CORREÇÃO*/

DELIMITER #



CREATE PROCEDURE LE_CURSO( P_IDCURSO INT )

BEGIN

                  SELECT NOME, HORAS, VALOR FROM CURSOS

                   WHERE IDCURSO =  P_IDCURSO;

END

#



DELIMITER ;



CALL LE_CURSO( 2 );



CREATE TABLE VENDEDORES(
	IDVENDENDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	JANEIRO FLOAT(10,2),
	FEVEREIRO FLOAT(10,2),
	MARCO FLOAT(10,2)
);

INSERT INTO VENDEDORES VALUES(NULL,'CARLOS','M',76234.78,88346.87,5756.90);
INSERT INTO VENDEDORES VALUES(NULL,'MARIA','F',5865.78,6768.87,4467.90);
INSERT INTO VENDEDORES VALUES(NULL,'ANTONIO','M',78769.78,6685.87,6664.90);
INSERT INTO VENDEDORES VALUES(NULL,'CLARA','F',5779.78,446886.87,8965.90);
INSERT INTO VENDEDORES VALUES(NULL,'ANDERSON','M',676545.78,77544.87,578665.90);
INSERT INTO VENDEDORES VALUES(NULL,'IVONE','F',57789.78,44774.87,68665.90);
INSERT INTO VENDEDORES VALUES(NULL,'JOAO','M',4785.78,66478.87,6887.90);
INSERT INTO VENDEDORES VALUES(NULL,'CELIA','F',89667.78,57654.87,5755.90);


/* MAX - TRAZ O VALOR MAXIMO DE UMA COLUNA*/

SELECT MAX(FEVEREIRO) AS MAIOR_FEV
FROM VENDEDORES; 


/* MIN - TRAZ O VALOR MINIMO DE UMA COLUNA*/

SELECT MIN(FEVEREIRO) AS MENOR_FEV
FROM VENDEDORES; 


/* AVG - TRAZ O VALOR MEDIO DE UMA COLUNA*/

SELECT AVG(FEVEREIRO) AS MEDIA_FEV
FROM VENDEDORES;

/* VARIAS FUNCOES*/ 

SELECT MAX(JANEIRO) AS MAC_JAN,
	MIN(JANEIRO) AS MIN_JAN,
	AVG(JANEIRO) AS MEDIA_JAN
	FROM VENDEDORES;


/* TRUNCATE */ 

SELECT MAX(JANEIRO) AS MAX_JAN, 
	MIN(JANEIRO) AS MIN_JAN,
	TRUNCATE(AVG(JANEIRO),2) AS MEDIA_JAN
	FROM VENDEDORES; 


/* AGREGANDO COM SUM()  SOMA OS VALORES DE UMA COLUNA*/

SELECT SUM(JANEIRO) AS TOTAL_JAN
FROM VENDEDORES; 


SELECT SUM(JANEIRO) AS TOTAL_JAN,
		SUM(FEVEREIRO) AS TOTAL_FEV,
		SUM(MARCO) AS TOTAL_MAR

FROM VENDEDORES; 

/*VENDAS POR SEXO*/

SELECT SEXO, SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDORES
GROUP BY SEXO; 

/* SUBQUERIES*/

/* VENDEDOR QUE VENDEU MENOS EM MARCO E SEU NOME*/ 
SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);


/* nome e o valor que vendeu mais em marco*/
SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);


/*quem vendeu mais que o valor medio de fev*/
SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);

SELECT AVG(FEVEREIRO) FROM VENDEDORES;

SELECT NOME, FEVEREIRO FROM VENDEDORES
WHERE FEVEREIRO < (SELECT AVG(FEVEREIRO) FROM VENDEDORES);


/* OPERAÇÕES EM LINHAS*/

SELECT * FROM VENDEDORES;

SELECT NOME,
		JANEIRO, 
		FEVEREIRO, 
		MARCO,
		(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
		TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS "MEDIA"
		FROM VENDEDORES;

/*CRIANDO UMA VIEW*/

CREATE VIEW V_RELATORIO AS
SELECT NOME,
		JANEIRO, 
		FEVEREIRO, 
		MARCO,
		(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
		TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS "MEDIA"
		FROM VENDEDORES;

;


/* APLICANDO UM %*/


SELECT NOME,
		JANEIRO, 
		FEVEREIRO, 
		MARCO,
		(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
		(JANEIRO+FEVEREIRO+MARCO) * .25 AS "DESCONTO",
		TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS "MEDIA"
		FROM VENDEDORES;
